#!/usr/bin/env bash
# discover-standards.sh — learn how THIS repo writes code and record it in .ai/standards.md,
# so any agent (Claude, Codex, Cursor…) writes new code that matches. Zero dependencies;
# deterministic. Declared tool config is authoritative; a few values are inferred from samples.
# Regenerate when tooling config changes (a git hook does this automatically after --project).
set -euo pipefail
ROOT="$(pwd)"
OUT="$ROOT/.ai/standards.md"
mkdir -p "$ROOT/.ai"
[ ! -L "$OUT" ] || { echo "refusing symlink output: $OUT" >&2; exit 1; }
[ ! -f "$OUT" ] || grep -Eq 'Generated by `(scripts|\.coder-ai-os-script|\.coder-ai/scripts)/discover-standards\.sh`' "$OUT" || { echo "kept user-owned standards: $OUT"; exit 0; }

list_files() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then git ls-files
  else find . -type f -not -path './.git/*' -not -path './node_modules/*' | sed 's|^\./||'; fi
}
FILES="$(list_files || true)"
has() { [ -f "$ROOT/$1" ]; }

{
  echo "# Code standards (auto-discovered) — match this before writing code"
  echo
  echo "> Generated by \`.coder-ai/scripts/discover-standards.sh\`. Declared tool config is authoritative;"
  echo "> \"inferred\" lines are heuristics from sample files. A repo's own config always wins."
  echo
  echo "## Declared tooling"
  found=0
  for f in .editorconfig .prettierrc .prettierrc.json .prettierrc.yaml .prettierrc.yml \
           prettier.config.js biome.json .eslintrc .eslintrc.json .eslintrc.cjs .eslintrc.js \
           tsconfig.json pyproject.toml setup.cfg .flake8 ruff.toml .rubocop.yml rustfmt.toml \
           .golangci.yml .clang-format Makefile; do
    if has "$f"; then echo "- \`$f\`"; found=1; fi
  done
  [ "$found" = 1 ] || echo "- (none found — infer from neighboring files + match the surrounding code)"
  echo

  if printf '%s\n' "$FILES" | grep -qE '\.(ts|tsx|js|jsx|mjs|cjs)$'; then
    echo "## JavaScript / TypeScript"
    echo "- package manager: $(has pnpm-lock.yaml && echo pnpm || { has yarn.lock && echo yarn || { has bun.lockb && echo bun || echo npm; }; })"
    if has tsconfig.json; then
      grep -qE '"strict"[[:space:]]*:[[:space:]]*true' "$ROOT/tsconfig.json" 2>/dev/null \
        && echo "- TypeScript: strict (no implicit any)" || echo "- TypeScript: present"
    fi
    for pf in .prettierrc .prettierrc.json prettier.config.js biome.json; do
      has "$pf" || continue
      grep -qE 'singleQuote"?[[:space:]]*:[[:space:]]*true' "$ROOT/$pf" 2>/dev/null && echo "- quotes: single (prettier)"
      grep -qE 'semi"?[[:space:]]*:[[:space:]]*false' "$ROOT/$pf" 2>/dev/null && echo "- semicolons: omitted (prettier)"
      break
    done
    printf '%s\n' "$FILES" | grep -qE 'vitest|\.test\.[tj]sx?$|__tests__/' && echo "- tests: jest/vitest (see config)"
    echo
  fi

  # Emit the Python section only when it has real signal — an empty "## Python" header
  # costs tokens in every session and tells the agent nothing.
  if printf '%s\n' "$FILES" | grep -qE '\.py$'; then
    pysec=""
    if has pyproject.toml; then
      grep -qE '\[tool\.black\]' "$ROOT/pyproject.toml" 2>/dev/null && pysec="${pysec}- formatter: black"$'\n'
      grep -qE '\[tool\.ruff\]|^ruff' "$ROOT/pyproject.toml" 2>/dev/null && pysec="${pysec}- linter: ruff"$'\n'
      grep -qE '\[tool\.isort\]' "$ROOT/pyproject.toml" 2>/dev/null && pysec="${pysec}- imports: isort"$'\n'
      grep -qE '\[tool\.mypy\]|mypy' "$ROOT/pyproject.toml" 2>/dev/null && pysec="${pysec}- types: mypy (annotate)"$'\n'
      ll="$(grep -oE 'line-length[[:space:]]*=[[:space:]]*[0-9]+' "$ROOT/pyproject.toml" 2>/dev/null | head -1 | grep -oE '[0-9]+' || true)"
      [ -z "$ll" ] || pysec="${pysec}- line length: ${ll}"$'\n'
    fi
    printf '%s\n' "$FILES" | grep -qE 'test_|_test\.py$|conftest\.py' && pysec="${pysec}- tests: pytest"$'\n'
    if [ -n "$pysec" ]; then echo "## Python"; printf '%s' "$pysec"; echo; fi
  fi

  echo "## Inferred (from sample files)"
  sample="$(printf '%s\n' "$FILES" | grep -E '\.(ts|tsx|js|jsx|py|go|rb|rs|java|kt)$' | head -25 || true)"
  if [ -n "$sample" ]; then
    args=(); while IFS= read -r sf; do [ -f "$ROOT/$sf" ] && args+=("$ROOT/$sf"); done <<EOF
$sample
EOF
    if [ "${#args[@]}" -gt 0 ]; then
      awk '/^\t/{t++} /^  [^ ]/{s++} END{print "- indentation: " ((t>s)?"tabs":"spaces (2)")}' "${args[@]}"
    fi
  else
    echo "- (no source sample — match the file you are editing)"
  fi
} > "$OUT"
echo "wrote $OUT"
