#!/usr/bin/env bash
# update-ai-context.sh — generate deterministic repo orientation metadata into
# .ai/PROJECT_SNAPSHOT.md. Zero dependencies (bash + coreutils only). No network,
# no third-party tools. Run from a repo root; re-run only when structural files
# change (new top-level dirs, build files, test layout). It is the always-available
# floor beneath an optional code index (e.g. CodeGraph MCP) — see AI_DEV_PROTOCOL.md.
#
# The output is purely STRUCTURAL and diff-stable (no timestamps/SHAs) so it only
# changes when the repo's shape changes. It NEVER prints file *contents* — only
# paths, extensions, and counts — so secrets in .env* are never emitted.
set -euo pipefail

ROOT="$(pwd)"
OUT_DIR="$ROOT/.ai"
OUT="$OUT_DIR/PROJECT_SNAPSHOT.md"

# File list: prefer git (respects .gitignore, skips node_modules if ignored),
# else fall back to find with common noise excluded.
list_files() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git ls-files
  else
    find . -type f \
      -not -path './.git/*' \
      -not -path './node_modules/*' \
      -not -path './.venv/*' -not -path './venv/*' \
      -not -path './dist/*' -not -path './build/*' \
      -not -path './.codegraph/*' \
      | sed 's|^\./||'
  fi
}

FILES="$(list_files || true)"

mkdir -p "$OUT_DIR"

# The report body is best-effort formatting: `head -N` truncation legitimately makes
# upstream commands exit via SIGPIPE (141), and empty grep matches return 1. Relax
# errexit/pipefail here so a truncated or empty section never aborts the whole write.
set +e +o pipefail

{
  echo "# Project Snapshot"
  echo
  echo "> Generated by \`scripts/update-ai-context.sh\` — do not hand-edit."
  echo "> Deterministic structural facts only. Regenerate when the repo's shape changes."
  echo "> For symbol/caller/impact queries prefer the code index (CodeGraph MCP) if present;"
  echo "> this file is the orientation fallback. Read it only when repo-wide orientation is needed."
  echo

  echo "## Languages (by tracked file extension)"
  echo '```'
  printf '%s\n' "$FILES" \
    | sed -n 's|.*/||; s|^.*\.\([A-Za-z0-9_]*\)$|\1|p' \
    | grep -vE '^[0-9]+$' \
    | sort | uniq -c | sort -nr | head -15
  echo '```'
  echo

  echo "## Top-level structure (depth 2)"
  echo '```'
  find . -maxdepth 2 \
    -not -path './.git' -not -path './.git/*' \
    -not -path './node_modules' -not -path './node_modules/*' \
    -not -path '*/.env*' \
    -not -path './.codegraph' -not -path './.codegraph/*' \
    2>/dev/null | sed 's|^\./||' | sort | head -200
  echo '```'
  echo

  echo "## Build / manifest files"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(package\.json|pnpm-workspace\.yaml|tsconfig\.json|pyproject\.toml|setup\.py|requirements\.txt|Cargo\.toml|go\.mod|pom\.xml|build\.gradle|Gemfile|composer\.json|Makefile|CMakeLists\.txt|Dockerfile|docker-compose\.ya?ml)$' \
    | sort || echo "(none found)"
  echo '```'
  echo

  echo "## Entry points (heuristic)"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(main|index|app|server|cli|__main__)\.[A-Za-z]+$|(^|/)cmd/[^/]+/main\.go$' \
    | sort | head -40 || echo "(none found)"
  echo '```'
  echo

  echo "## Test directories"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(tests?|__tests__|spec|e2e)/' \
    | sed 's|/[^/]*$||' | sort -u | head -50 || echo "(none found)"
  echo '```'
} > "$OUT"

set -e -o pipefail

echo "wrote $OUT"
