#!/usr/bin/env bash
# update-ai-context.sh — generate deterministic repo orientation metadata into
# .ai/PROJECT_SNAPSHOT.md. Zero dependencies (bash + coreutils only). No network,
# no third-party tools. Run from a repo root; re-run only when structural files
# change (new top-level dirs, build files, test layout). It is the always-available
# floor beneath an optional code index (e.g. CodeGraph MCP) — see AI_DEV_PROTOCOL.md.
#
# The output is purely STRUCTURAL and diff-stable (no timestamps/SHAs) so it only
# changes when the repo's shape changes. It NEVER prints file *contents* — only
# paths, extensions, and counts — so secrets in .env* are never emitted.
set -euo pipefail

ROOT="$(pwd)"
OUT_DIR="$ROOT/.ai"
OUT="$OUT_DIR/PROJECT_SNAPSHOT.md"

# File list: prefer git (respects .gitignore, skips node_modules if ignored),
# else fall back to find with common noise excluded.
list_files() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # --others --exclude-standard: files created mid-task matter for orientation too.
    git ls-files --cached --others --exclude-standard
  else
    find . -type f \
      -not -path './.git/*' \
      -not -path './node_modules/*' \
      -not -path './.venv/*' -not -path './venv/*' \
      -not -path './dist/*' -not -path './build/*' \
      -not -path './.codegraph/*' \
      | sed 's|^\./||'
  fi
}

# Memory scope: is .ai/ shared through git or machine-local? Agents must know which world
# they are in — shared state is committed with features and teammates resume from it;
# local-only state must NEVER be git-added and cannot be assumed visible to anyone else.
memory_scope() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "local-only (no git repo)"; return; }
  if git check-ignore -q .ai 2>/dev/null; then
    echo "LOCAL-ONLY (.ai is git-ignored): never git-add it; teammates/CI cannot see this state; a fresh clone reconstructs from code + git log"
  elif [ -n "$(git ls-files .ai 2>/dev/null | head -1)" ]; then
    echo "SHARED (.ai is tracked): commit .ai updates with the feature — checkpoint + artifacts are the team's resume state and why-history"
  else
    echo "LOCAL-ONLY so far (.ai untracked): the human decides — commit .ai/memory + epic artifacts to share resume state, or add .ai/ to .gitignore to keep it machine-local"
  fi
}

# .ai/ is the agents' meta workspace (snapshot, memory, epic artifacts) — not project shape.
# Excluding it keeps the fingerprint stable across checkpoint/artifact churn and stops the
# snapshot from flagging itself stale (it is created after this list is computed).
FILES="$(list_files | grep -v '^\.ai/' || true)"
FINGERPRINT="$(printf '%s\n' "$FILES" | LC_ALL=C sort | cksum | awk '{print $1" "$2}')"

# ---------- code atlas (L1 INDEX / L2 unit / L3 folder maps), generated ON DEMAND ----------
# A unit is any directory: a manifest package, a bare top-level source dir, or the repo
# root ("."). The atlas is a hierarchy of markdown maps replacing the old .tsv indexes:
#   .ai/symbols/INDEX.md            L1  repo: units + manifest dependency graph
#   .ai/symbols/<unit>.md           L2  unit: folder import graph + folder table + root files
#   .ai/symbols/<unit>/<folder>.md  L3  folder: file import graph + per-file symbol tables
# Tables carry name | kind | line, so L1 symbol lookup stays one grep:
#   rg -w '<name>' .ai/symbols/
# Edges come from PARSED IMPORT LINES (py/ts/js) resolved against the repo file list —
# exact counts, not word-match guesses. Other languages get maps without import edges
# (stated in the file) until their resolvers exist. Names and locations only, never code.
#
# OWNERSHIP IS EXCLUSIVE: a unit's maps cover only files no NESTED unit claims, so each
# file appears in exactly one map and root.md holds just the unclaimed leftovers.
SRC_EXT_RE='\.(py|ts|tsx|js|jsx|go|rs|rb|java|php|cs|sh)$'
MD_MIN_FILES="${MD_MIN_FILES:-8}"   # a folder subtree with >= this many owned files gets its own L3 map
GEN_MARK='Generated by .coder-ai-os-script/update-ai-context.sh'

# Unit list for ownership comes from the snapshot; without one (bare --symbols run in a
# repo that never generated it) ownership falls back to whole-subtree. --symbols-all
# always regenerates the snapshot first, so sync/setup paths get exclusive ownership.
UNITS_ALL="$({ [ -f "$OUT" ] && awk '/  map: \.ai\/symbols\//{print $1}' "$OUT" | sort -u; } || true)"

unit_subunits() {  # <dir> -> units strictly nested inside it (their files are NOT ours)
  [ -n "$UNITS_ALL" ] || return 0
  local u
  while IFS= read -r u; do
    [ -n "$u" ] && [ "$u" != "$1" ] && [ "$u" != "." ] || continue
    if [ "$1" = "." ]; then printf '%s\n' "$u"
    else case "$u" in "$1"/*) printf '%s\n' "$u" ;; esac; fi
  done <<UEOF
$UNITS_ALL
UEOF
}

unit_name() {  # <dir> -> map path MIRRORING the folder structure, collision-safe:
  # real paths are unique, so mirroring them can't collide (manifest names could —
  # two packages named "api" must not share one map). ".." never survives (traversal),
  # and a literal top-level "root" dir must not collide with the repo-root map.
  local d="$1" n
  [ "$d" = "." ] && { echo root; return; }
  n="$(printf '%s' "$d" | sed 's|^\./||; s|\.\.|__|g; s|[^A-Za-z0-9._/-]|_|g; s|/\{2,\}|/|g; s|^[/_-]*||; s|[/_-]*$||')"
  [ "$n" = "root" ] && n="root_dir"
  printf '%s' "${n:-unit}"
}

# The repo root has no separate map: INDEX.md IS the root map (packages graph + any
# unclaimed root-level files) — two files doing one job confused more than they helped.
map_out() { if [ "$1" = "." ]; then echo ".ai/symbols/INDEX.md"; else echo ".ai/symbols/$(unit_name "$1").md"; fi; }

unit_files() {  # <dir> -> source files OWNED by the unit (repo-relative); empty is legal.
  # Owned = in the unit's subtree but NOT in a nested unit's subtree (exclusive ownership).
  # The root unit skips dot-directories (.claude/, .lefthook/, …): agent/tooling config,
  # not project code — it must not pollute root.md, which holds real unclaimed leftovers.
  local subs; subs="$(unit_subunits "$1")"
  { if [ "$1" = "." ]; then printf '%s\n' "$FILES" | grep -E "$SRC_EXT_RE" | grep -v '^\.' || true
    else printf '%s\n' "$FILES" | grep -E "^$1/" | grep -E "$SRC_EXT_RE" || true; fi
  } | if [ -n "$subs" ]; then
    awk 'NR == FNR { p[++n] = $0 "/"; next }
      { for (i = 1; i <= n; i++) if (index($0, p[i]) == 1) next; print }' \
      <(printf '%s\n' "$subs") -
  else cat; fi
}

unit_fingerprint() {  # <dir> -> content checksum over the unit's source files
  unit_files "$1" | LC_ALL=C sort | while IFS= read -r f; do [ -f "$f" ] && cksum "$f"; done \
    | cksum | awk '{print $1" "$2}'
}

extract_symbols() {  # stdin: file list -> rows "file<TAB>kind<TAB>name<TAB>line"
  if command -v ctags >/dev/null 2>&1 && ctags --version 2>/dev/null | grep -qi universal; then
    ctags -x --sort=no -L - 2>/dev/null \
      | awk '{ printf "%s\t%s\t%s\t%s\n", $4, $2, $1, $3 }'
    return
  fi
  # Zero-dep regex fallback: DEFINITIONS only (call edges need a real parser and would lie).
  # NUL-delimited xargs: filenames with spaces must not split into unopenable args.
  tr '\n' '\0' | xargs -0 -r awk '
    function ident(s) { if (match(s, /[A-Za-z_][A-Za-z0-9_]*/)) return substr(s, RSTART, RLENGTH); return "" }
    function emit(kind, s) { n = ident(s); if (n != "") printf "%s\t%s\t%s\t%d\n", FILENAME, kind, n, FNR }
    FNR == 1 { ext = FILENAME; sub(/.*\./, "", ext) }
    ext == "py" && $0 ~ /^[ \t]*(async[ \t]+)?def[ \t]+[A-Za-z_]/     { t=$0; sub(/^[ \t]*(async[ \t]+)?def[ \t]+/, "", t); emit("function", t) }
    ext == "py" && $0 ~ /^[ \t]*class[ \t]+[A-Za-z_]/                  { t=$0; sub(/^[ \t]*class[ \t]+/, "", t); emit("class", t) }
    (ext == "ts" || ext == "tsx" || ext == "js" || ext == "jsx") && $0 ~ /^[ \t]*(export[ \t]+)?(default[ \t]+)?(async[ \t]+)?function[ \t]+[A-Za-z_$]/ { t=$0; sub(/^.*function[ \t]+/, "", t); emit("function", t) }
    (ext == "ts" || ext == "tsx" || ext == "js" || ext == "jsx") && $0 ~ /^[ \t]*(export[ \t]+)?(abstract[ \t]+)?(class|interface|enum)[ \t]+[A-Za-z_$]/ { t=$0; sub(/^[ \t]*(export[ \t]+)?(abstract[ \t]+)?(class|interface|enum)[ \t]+/, "", t); emit("class", t) }
    (ext == "ts" || ext == "tsx" || ext == "js" || ext == "jsx") && $0 ~ /^[ \t]*(export[ \t]+)?const[ \t]+[A-Za-z_$][A-Za-z0-9_$]*[ \t]*=[ \t]*(async[ \t]*)?(\(|[A-Za-z_$0-9]+[ \t]*=>)/ { t=$0; sub(/^[ \t]*(export[ \t]+)?const[ \t]+/, "", t); emit("function", t) }
    ext == "go" && $0 ~ /^func[ \t]/                                    { t=$0; sub(/^func[ \t]+(\([^)]*\)[ \t]*)?/, "", t); emit("function", t) }
    ext == "go" && $0 ~ /^type[ \t]+[A-Za-z_]/                          { t=$0; sub(/^type[ \t]+/, "", t); emit("type", t) }
    ext == "rs" && $0 ~ /^[ \t]*(pub[ \t(a-z)]*[ \t]+)?(async[ \t]+)?fn[ \t]+[A-Za-z_]/ { t=$0; sub(/^.*fn[ \t]+/, "", t); emit("function", t) }
    ext == "rs" && $0 ~ /^[ \t]*(pub[ \t(a-z)]*[ \t]+)?(struct|enum|trait)[ \t]+[A-Za-z_]/ { t=$0; sub(/^[ \t]*(pub[ \t(a-z)]*[ \t]+)?(struct|enum|trait)[ \t]+/, "", t); emit("type", t) }
    ext == "rb" && $0 ~ /^[ \t]*def[ \t]+[A-Za-z_]/                     { t=$0; sub(/^[ \t]*def[ \t]+/, "", t); emit("function", t) }
    ext == "rb" && $0 ~ /^[ \t]*(class|module)[ \t]+[A-Z]/              { t=$0; sub(/^[ \t]*(class|module)[ \t]+/, "", t); emit("class", t) }
    (ext == "java" || ext == "cs") && $0 ~ /^[ \t]*(public|private|protected|abstract|final|static|[ \t])*(class|interface|enum)[ \t]+[A-Za-z_]/ { t=$0; sub(/^.*(class|interface|enum)[ \t]+/, "", t); emit("class", t) }
    ext == "php" && $0 ~ /^[ \t]*(public[ \t]+|private[ \t]+|protected[ \t]+|static[ \t]+)*function[ \t]+[A-Za-z_]/ { t=$0; sub(/^.*function[ \t]+/, "", t); emit("function", t) }
    ext == "php" && $0 ~ /^[ \t]*(abstract[ \t]+|final[ \t]+)?(class|interface|trait)[ \t]+[A-Za-z_]/ { t=$0; sub(/^.*(class|interface|trait)[ \t]+/, "", t); emit("class", t) }
    ext == "sh" && $0 ~ /^[ \t]*(function[ \t]+)?[A-Za-z_][A-Za-z0-9_]*[ \t]*\(\)/ { t=$0; sub(/^[ \t]*(function[ \t]+)?/, "", t); emit("function", t) }
  '
}

extract_imports() {  # stdin: file list -> rows "srcfile<TAB>spec<TAB>lang" (raw, unresolved)
  tr '\n' '\0' | xargs -0 -r awk '
    FNR == 1 { ext = FILENAME; sub(/.*\./, "", ext) }
    ext == "py" && $0 ~ /^[ \t]*from[ \t]+[.A-Za-z0-9_]+[ \t]+import/ {
      s = $0; sub(/^[ \t]*from[ \t]+/, "", s); sub(/[ \t]+import.*/, "", s)
      printf "%s\t%s\tpy\n", FILENAME, s; next }
    ext == "py" && $0 ~ /^[ \t]*import[ \t]+[A-Za-z0-9_.]/ {
      s = $0; sub(/^[ \t]*import[ \t]+/, "", s)
      n = split(s, mods, /[ \t]*,[ \t]*/)
      for (i = 1; i <= n; i++) { m = mods[i]; sub(/[ \t].*/, "", m); if (m != "") printf "%s\t%s\tpy\n", FILENAME, m }
      next }
    (ext == "ts" || ext == "tsx" || ext == "js" || ext == "jsx") && match($0, /from[ \t]+['\''"][^'\''"]+['\''"]/) {
      s = substr($0, RSTART, RLENGTH); sub(/^from[ \t]+['\''"]/, "", s); sub(/['\''"]$/, "", s)
      printf "%s\t%s\tjs\n", FILENAME, s; next }
    (ext == "ts" || ext == "tsx" || ext == "js" || ext == "jsx") && match($0, /(require|import)\(['\''"][^'\''"]+['\''"]\)/) {
      s = substr($0, RSTART, RLENGTH); sub(/^(require|import)\(['\''"]/, "", s); sub(/['\''"]\)$/, "", s)
      printf "%s\t%s\tjs\n", FILENAME, s }
  '
}

resolve_imports() {  # <fileslist> <unitnames> <unitslist> <rawimports> -> "srcfile<TAB>dstfile"
  # Python: absolute modules probed under the SOURCE FILE'S OWN unit dir, then the repo
  # root, then the file's dir; relative modules from the file's dir. JS/TS: relative paths
  # with extension/index probes; bare specifiers matched against workspace package names
  # -> pseudo-edge "UNIT:<dir>". Unresolved imports (external libraries) are dropped.
  awk -v FILESLIST="$1" -v UNITNAMES="$2" -v UNITSLIST="$3" '
    function norm(p,   parts, out, i, n, m, r) {
      n = split(p, parts, "/"); m = 0
      for (i = 1; i <= n; i++) {
        if (parts[i] == "" || parts[i] == ".") continue
        if (parts[i] == "..") { if (m > 0) m--; continue }
        out[++m] = parts[i]
      }
      r = ""; for (i = 1; i <= m; i++) r = r (i > 1 ? "/" : "") out[i]
      return r
    }
    function dirof(f) { if (f !~ /\//) return ""; sub(/\/[^\/]*$/, "", f); return f }
    function hit(p) { p = norm(p); return (p in files) ? p : "" }
    function urootof(f,   i, best) { best = ""; for (i = 1; i <= nu; i++) if (index(f, units[i] "/") == 1 && length(units[i]) > length(best)) best = units[i]; return best }
    function pyprobe(root, mod,   b, r) {
      b = (root == "" ? "" : root "/") mod; gsub(/\./, "/", b)
      r = hit(b ".py"); if (r != "") return r
      return hit(b "/__init__.py")
    }
    function jsprobe(base,   i, r) {
      r = hit(base); if (r != "") return r
      for (i = 1; i <= 4; i++) { r = hit(base "." jsext[i]); if (r != "") return r }
      for (i = 1; i <= 4; i++) { r = hit(base "/index." jsext[i]); if (r != "") return r }
      return ""
    }
    BEGIN {
      split("ts tsx js jsx", jsext, " ")
      while ((getline l < FILESLIST) > 0) files[l] = 1
      while ((getline l < UNITNAMES) > 0) { k = index(l, "\t"); if (k > 1) { nm = substr(l, 1, k - 1); dd = substr(l, k + 1); if (nm != "" && nm != "?") uname[nm] = dd } }
      nu = 0
      while ((getline l < UNITSLIST) > 0) if (l != "" && l != ".") units[++nu] = l
      FS = "\t"
    }
    {
      src = $1; spec = $2; lang = $3; dst = ""
      if (lang == "py") {
        if (spec ~ /^\./) {
          k = 0; while (substr(spec, k + 1, 1) == ".") k++
          rest = substr(spec, k + 1); base = dirof(src)
          for (i = 1; i < k; i++) base = dirof(base)
          if (rest == "") dst = hit(base "/__init__.py")
          else dst = pyprobe(base, rest)
        } else {
          ur = urootof(src)
          dst = pyprobe(ur, spec)
          if (dst == "") dst = pyprobe("", spec)
          if (dst == "") dst = pyprobe(dirof(src), spec)
        }
      } else {
        if (spec ~ /^\./) dst = jsprobe(norm(dirof(src) "/" spec))
        else { p = spec; sub(/\/.*/, "", p); if (p in uname) dst = "UNIT:" uname[p] }
      }
      if (dst != "" && dst != src) print src "\t" dst
    }
  ' "$4"
}

# map_delta <oldcopy> <newfile> <label> — whenever a map is regenerated (by AI --refresh
# or a human --symbols/--symbols-all), show WHAT CHANGED: old vs new table rows (symbols)
# and mermaid edges. One line per changed map, on stderr (stdout is the written-paths
# protocol the GC consumes); silent when the map is unchanged.
map_delta() {
  local old="$1" new="$2" label="$3"
  [ -f "$new" ] || return 0
  if [ ! -s "$old" ]; then echo "Δ $label: NEW map" >&2; return 0; fi
  cmp -s "$old" "$new" && return 0
  awk -v L="$label" '
    function cell(s,   c) { split(s, c, /\|/); gsub(/^[ \t]+|[ \t]+$/, "", c[2]); return c[2] }
    function isrow(s) { return s ~ /^\| / && s !~ /^\| name \|/ && s !~ /^\|---/ }
    function isedge(s) { return s ~ /-->/ }
    NR == FNR { if (isrow($0)) { o[$0] = 1; on++ } else if (isedge($0)) oe[$0] = 1; next }
    isrow($0) { nn++; if ($0 in o) delete o[$0]; else { na++; if (na <= 4) ax = ax " +" cell($0) } ; next }
    isedge($0) { if ($0 in oe) delete oe[$0]; else ea++ }
    END {
      nr = 0; for (k in o) { nr++; if (nr <= 4) rx = rx " -" cell(k) }
      er = 0; for (k in oe) er++
      if (!(na || nr || ea || er)) exit   # metadata-only rewrite (fingerprint line) — not a change worth reporting
      msg = "Δ " L ": symbols " (on + 0) "→" (nn + 0)
      if (na || nr) msg = msg " (+" (na + 0) " −" (nr + 0) ":" ax rx ((na > 4 || nr > 4) ? " …" : "") ")"
      if (ea || er) msg = msg " · edges +" (ea + 0) " −" (er + 0) " (weight changes count)"
      print msg
    }
  ' "$old" "$new" >&2
}

# md_guard <path> — refuse symlinks and writes escaping .ai/symbols (hostile-clone defense)
md_guard() {
  [ ! -L .ai ] && [ ! -L .ai/symbols ] || { echo "refusing symlinked .ai/.ai-symbols" >&2; return 1; }
  mkdir -p "$(dirname "$1")"
  local pdir; pdir="$(cd "$(dirname "$1")" && pwd -P)" || return 1
  case "$pdir/" in "$(pwd -P)/.ai/symbols/"*) : ;; *) echo "refusing write outside .ai/symbols: $1" >&2; return 1 ;; esac
  [ ! -L "$1" ] || { echo "refusing symlink output: $1" >&2; return 1; }
}

emit_owner_tables() {  # <owner> <workdir> <mode> <heading-prefix> — every file section the
  # given owner claims, in ONE awk pass (a per-file pass would be O(files × symbols)).
  awk -F "\t" -v own="$1" -v mode="$3" -v hp="$4" -v ASG="$2/assign" -v UB="$2/usedby" -v ST="$2/status" '
    BEGIN {
      while ((getline t < ASG) > 0) { split(t, a, FS); if (a[1] == own) { rel[a[2]] = a[3]; ord[++n] = a[2] } }
      if (mode == "rich") {
        while ((getline t < UB) > 0) { k = index(t, "\t"); if (k > 1) ub[substr(t, 1, k - 1)] = substr(t, k + 1) }
        while ((getline t < ST) > 0) { split(t, a, FS); st[a[1] SUBSEP a[2] SUBSEP a[3]] = a[4] }
      }
    }
    ($1 in rel) {
      if (mode == "rich") {
        u = (($3 in ub) ? ub[$3] : "")
        s = (($3 SUBSEP $1 SUBSEP $4) in st ? st[$3 SUBSEP $1 SUBSEP $4] : (u != "" ? "used" : ""))
        rows[$1] = rows[$1] sprintf("| %s | %s | %s | %s | %s |\n", $3, $2, $4, u, s)
      } else rows[$1] = rows[$1] sprintf("| %s | %s | %s |\n", $3, $2, $4)
    }
    END {
      for (i = 1; i <= n; i++) {
        f = ord[i]
        printf "\n%s %s\n\n", hp, rel[f]
        if (mode == "rich") print "| name | kind | line | used by | status |\n|---|---|---|---|---|"
        else print "| name | kind | line |\n|---|---|---|"
        printf "%s", rows[f]
      }
    }
  ' "$2/syms"
}

# write_unit_maps <dir> [rich] — L2 unit map + its L3 folder maps. "rich" adds used-by +
# classification (word-match confirmed by import edges; tests/entries/private classified
# BEFORE anything is flagged "verify"). Prints every file it wrote, one per line.
write_unit_maps() {
  local d="$1" mode="${2:-plain}" u out fp UW rel fout dots i
  u="$(unit_name "$d")"; out="$(map_out "$d")"
  md_guard "$out" || return 1
  UW="$(mktemp -d)"
  [ ! -f "$out" ] || cp "$out" "$UW/prev_l2"
  unit_files "$d" | LC_ALL=C sort > "$UW/files"
  fp="$(while IFS= read -r f; do [ -f "$f" ] && cksum "$f"; done < "$UW/files" | cksum | awk '{print $1" "$2}')"
  extract_symbols < "$UW/files" > "$UW/syms" || true
  # workspace package names (manifest rows only) for cross-unit js resolution
  { [ -f "$OUT" ] && awk '/  map: \.ai\/symbols\// && $2 ~ /^\[/ { print $3 "\t" $1 }' "$OUT"; } > "$UW/unames" || true
  printf '%s\n' "$FILES" > "$UW/allfiles"
  printf '%s\n' "$UNITS_ALL" > "$UW/unitslist"
  if [ "$mode" = "rich" ]; then printf '%s\n' "$FILES" | grep -E "$SRC_EXT_RE" | extract_imports > "$UW/raw" || true
  else extract_imports < "$UW/files" > "$UW/raw" || true; fi
  resolve_imports "$UW/allfiles" "$UW/unames" "$UW/unitslist" "$UW/raw" > "$UW/edges" || true
  : > "$UW/usedby"; : > "$UW/status"
  if [ "$mode" = "rich" ]; then
    cut -f3 "$UW/syms" | grep -Ev '^__.*__$' | LC_ALL=C sort -u > "$UW/names" || true
    if [ -s "$UW/names" ]; then
      printf '%s\n' "$FILES" | grep -E "$SRC_EXT_RE" | tr '\n' '\0' \
        | xargs -0 -r grep -nwHFf "$UW/names" -- 2>/dev/null > "$UW/hits" || true
      # used-by: hits kept only when the using file is the defining file or imports it
      awk -v SYMS="$UW/syms" -v EDGES="$UW/edges" '
        BEGIN {
          FS = "\t"
          while ((getline t < SYMS) > 0) { split(t, a, FS); if (!(a[3] in owner)) { owner[a[3]] = a[1]; defl[a[3]] = a[4] + 0 } }
          while ((getline t < EDGES) > 0) { split(t, a, FS); imp[a[1] SUBSEP a[2]] = 1 }
        }
        {
          p1 = index($0, ":"); rest = substr($0, p1 + 1); p2 = index(rest, ":")
          f = substr($0, 1, p1 - 1); l = substr(rest, 1, p2 - 1) + 0; c = substr(rest, p2 + 1)
          m = split(c, toks, /[^A-Za-z0-9_$]+/)
          for (i = 1; i <= m; i++) {
            s = toks[i]
            if (!(s in owner) || ((s, f, l) in seen)) continue
            seen[s, f, l] = 1
            df = owner[s]
            if (f == df && l == defl[s]) continue
            if (f != df && !((f SUBSEP df) in imp)) continue
            uc[s]++
            if (uc[s] <= 4) ub[s] = (ub[s] == "" ? "" : ub[s] " · ") f ":" l
          }
        }
        END { for (s in uc) print s "\t" ub[s] (uc[s] > 4 ? " (+" (uc[s] - 4) ")" : "") }
      ' "$UW/hits" > "$UW/usedby" || true
      # unreferenced symbols -> classify: test / entry (decorated) / private / verify
      awk -F "\t" 'NR == FNR { k = index($0, "\t"); if (k > 1) used[substr($0, 1, k - 1)] = 1; next }
                   !($3 in used) { print $1 "\t" $3 "\t" $4 }' "$UW/usedby" "$UW/syms" > "$UW/unref" || true
      awk -F "\t" '{ print $1 }' "$UW/unref" | sort -u | tr '\n' '\0' | xargs -0 -r awk '
        { line[FILENAME SUBSEP FNR] = $0 }
        END { for (k in line) if (line[k] ~ /^[ \t]*@/) { split(k, a, SUBSEP); print a[1] "\t" a[2] + 1 } }
      ' 2>/dev/null | sort -u > "$UW/decorated" || true
      awk -F "\t" -v DEC="$UW/decorated" '
        BEGIN { while ((getline t < DEC) > 0) { split(t, a, "\t"); dec[a[1] SUBSEP a[2]] = 1 } }
        {
          f = $1; n = $2; l = $3; st = "verify"
          if (f ~ /(^|\/)tests?\//) st = "test"
          else if (n ~ /^(test_|Test)/) st = "test"
          else if ((f SUBSEP l) in dec) st = "entry"
          else if (n ~ /^_/) st = "private"
          print n "\t" f "\t" l "\t" st
        }
      ' "$UW/unref" > "$UW/status" || true
    fi
  fi
  # L3 assignment: the DEEPEST folder (relative to the unit) whose subtree owns
  # >= MD_MIN_FILES files claims each file; unclaimed files land in the unit map itself.
  awk -v d="$d" -v minf="$MD_MIN_FILES" '
    { rel = (d == "." ? $0 : substr($0, length(d) + 2)); full[NR] = $0; relf[NR] = rel; n = NR
      p = rel; while (p ~ /\//) { sub(/\/[^\/]*$/, "", p); cnt[p]++ } }
    END {
      for (i = 1; i <= n; i++) {
        best = ""; p = relf[i]
        while (p ~ /\//) { sub(/\/[^\/]*$/, "", p); if (cnt[p] >= minf) { best = p; break } }
        # "-" = owned by the unit map itself (an empty first field would be eaten by
        # read/IFS leading-whitespace stripping — tab is IFS whitespace).
        print (best == "" ? "-" : best) "\t" full[i] "\t" relf[i]
      }
    }
  ' "$UW/files" > "$UW/assign"
  # ---- L2 unit map
  {
    echo "# map: $d"
    echo
    echo "> $GEN_MARK — do not hand-edit. Regenerate: .coder-ai-os-script/update-ai-context.sh --symbols $d"
    echo "> fingerprint: $fp (content checksum) — check freshness: --symbols $d --check"
    echo ">"
    echo "> QUERY this map — NEVER read it whole (thousands of rows; loading it burns the"
    echo "> context a query answers in one line). Take ONLY what the current task needs:"
    echo ">   find a symbol:       rg -w '<name>' .ai/symbols/          -> | name | kind | line |"
    echo ">   this unit's wiring:  sed -n '/^## folders/,/^\`\`\`\$/p' $out"
    echo ">   one file's symbols:  sed -n '/^### <file>/,/^### /p' $out   (folder maps use ##)"
    echo "> Task finished (code edited)? .coder-ai-os-script/update-ai-context.sh --refresh — remaps only"
    echo "> what you touched, tracing which files are done."
    [ "$mode" = "rich" ] || echo "> Enrich with used-by + classification: .coder-ai-os-script/update-ai-context.sh --graph $d"
    echo
    echo "symbols: $(grep -c . "$UW/syms" || true) · files: $(grep -c . "$UW/files" || true)"
    echo
    echo "## folders (import edges, measured)"
    echo
    echo '```mermaid'
    echo 'flowchart TB'
    awk -v d="$d" '
      # Aggregate to depth-2 folders (app/api, app/use_cases) so a single dominant top
      # folder still shows its internal architecture; fall back to depth-1 when depth-2
      # would be a hairball (> 24 nodes).
      function relof(f,   r) {
        if (d == ".") return f
        if (index(f, d "/") == 1) return substr(f, length(d) + 2)
        return ""
      }
      function level(f, k,   r, parts, m, i, out) {
        r = relof(f); if (r == "") return ""
        m = split(r, parts, "/"); if (m == 1) return "(root)"
        out = parts[1]
        if (k >= 2 && m > 2) out = out "/" parts[2]
        return out
      }
      function addedge(k, s, t) { if (s == "" || t == "" || s == t) return; ek = s "\t" t; if (k == 1) e1[ek]++; else { e2[ek]++; n2s[s] = 1; n2s[t] = 1 } }
      BEGIN { FS = "\t" }
      {
        if ($2 ~ /^UNIT:/) { dst1 = "→ " substr($2, 6); dst2 = dst1 }
        else {
          dst1 = level($2, 1); dst2 = level($2, 2)
          if (dst1 == "") { t = $2; sub(/\/[^\/]*$/, "", t); dst1 = "→ " t; dst2 = dst1 }
        }
        src1 = level($1, 1); src2 = level($1, 2)
        addedge(1, src1, dst1); addedge(2, src2, dst2)
      }
      END {
        nn = 0; for (s in n2s) nn++
        if (nn > 0 && nn <= 24) { for (k in e2) out[k] = e2[k] } else { for (k in e1) out[k] = e1[k] }
        if (length(out) == 0) { print "  none[\"no import edges found (unsupported language or flat unit)\"]"; exit }
        for (k in out) {
          split(k, a, "\t")
          printf "  %s[\"%s\"] -->|%d| %s[\"%s\"]\n", mid(a[1]), a[1], out[k], mid(a[2]), a[2]
        }
      }
      function mid(s) {
        gsub(/[^A-Za-z0-9_]/, "_", s)
        if (s ~ /^[^A-Za-z]/ || s ~ /^(end|graph|subgraph|flowchart|direction|click|style|class|classDef|linkStyle|default)$/) s = "n_" s
        return s
      }
    ' "$UW/edges" | LC_ALL=C sort -u
    echo '```'
    echo
    echo "## folder maps"
    echo
    echo "| folder | files | map |"
    echo "|---|---|---|"
    awk -F "\t" -v u="$u" '$1 != "-" { c[$1]++ } END { if (length(c) == 0) print "| (none) | | |"; for (p in c) printf "| %s | %d | [%s](%s/%s.md) |\n", p, c[p], p, u, p }' "$UW/assign" | LC_ALL=C sort
    if [ "$mode" = "rich" ] && [ -s "$UW/status" ]; then
      echo
      echo "## needs verification (no confirmed reference; not a test/entry/private)"
      echo
      # cap inside awk — an external `| head` SIGPIPEs the whole emission under set -e
      awk -F "\t" '
        $4 == "verify" { nv++; if (nv <= 40) print "- " $1 " — " $2 ":" $3 }
        END { if (nv > 40) print "- … +" (nv - 40) " more (see the folder maps below)" }
      ' "$UW/status"
    fi
    if awk -F "\t" '$1 == "-" { found = 1 } END { exit !found }' "$UW/assign"; then
      echo
      echo "## files at unit level"
      emit_owner_tables "-" "$UW" "$mode" "###"
    fi
  } > "$out"
  map_delta "$UW/prev_l2" "$out" "$out"
  echo "$out"
  # ---- L3 folder maps
  while IFS= read -r rel; do
    [ -n "$rel" ] || continue
    fout="$(map_out "$d/$rel")"
    md_guard "$fout" || { rm -rf "$UW"; return 1; }
    [ ! -f "$fout" ] || cp "$fout" "$UW/prev_l3"; [ -f "$fout" ] || : > "$UW/prev_l3"
    dots=""; i="$rel"; while [ "${i#*/}" != "$i" ]; do dots="../$dots"; i="${i#*/}"; done; dots="../$dots"
    {
      echo "# map: $d/$rel"
      echo
      echo "> $GEN_MARK — part of [$u.md](${dots}$(basename "$out")). Regenerate: .coder-ai-os-script/update-ai-context.sh --symbols $d"
      echo "> QUERY, never read whole: rg -w '<name>' .ai/symbols/ finds any symbol in one line;"
      echo "> one file's table: sed -n '/^## <file>/,/^## /p' $fout. Load only what the task needs."
      echo
      echo "## files (import edges within this folder)"
      echo
      echo '```mermaid'
      awk -F "\t" -v scope="$d/$rel/" '
        function short(f) { return substr(f, length(scope) + 1) }
        {
          if ($2 ~ /^UNIT:/) next
          if (index($1, scope) == 1 && index($2, scope) == 1) e[short($1) "\t" short($2)]++
          else if (index($1, scope) == 1) outn++
        }
        END {
          print "flowchart LR"
          if (length(e) == 0) { print "  none[\"no internal import edges\"]" }
          shown = 0
          for (k in e) {
            if (++shown > 60) { printf "  %%%% +%d more edges\n", length(e) - 60; break }
            split(k, a, "\t")
            printf "  %s[\"%s\"] -->|%d| %s[\"%s\"]\n", mid(a[1]), a[1], e[k], mid(a[2]), a[2]
          }
          if (outn) printf "  %%%% %d imports leave this folder — see the unit map\n", outn
        }
        function mid(s) {
          gsub(/[^A-Za-z0-9_]/, "_", s)
          if (s ~ /^[^A-Za-z]/ || s ~ /^(end|graph|subgraph|flowchart|direction|click|style|class|classDef|linkStyle|default)$/) s = "n_" s
          return s
        }
      ' "$UW/edges"
      echo '```'
      emit_owner_tables "$rel" "$UW" "$mode" "##"
    } > "$fout"
    map_delta "$UW/prev_l3" "$fout" "$fout"
    echo "$fout"
  done < <(awk -F "\t" '$1 != "-" { print $1 }' "$UW/assign" | LC_ALL=C sort -u)
  rm -rf "$UW"
}

write_index_md() {  # L1: units + manifest dependency graph, from the snapshot rows
  local out=".ai/symbols/INDEX.md" PREV=""
  md_guard "$out" || return 1
  if [ -f "$out" ]; then PREV="$(mktemp)"; cp "$out" "$PREV"; fi
  {
    echo "# code atlas"
    echo
    echo "> $GEN_MARK — do not hand-edit. Regenerate: .coder-ai-os-script/update-ai-context.sh --symbols-all"
    echo "> Fingerprint: $FINGERPRINT (path-list checksum, same as the snapshot)."
    echo "> QUERY the atlas, never bulk-read it: rg -w '<name>' .ai/symbols/ answers a symbol"
    echo "> lookup in ONE line; open a unit/folder map SECTION only when the task needs that"
    echo "> unit's wiring. After a task that edits code: .coder-ai-os-script/update-ai-context.sh --refresh"
    echo "> Graphs: VS Code 1.121+ renders mermaid natively in markdown preview — if diagrams"
    echo "> don't show, UNINSTALL bierner.markdown-mermaid (it now conflicts) or use mermaid.live."
    echo
    echo "## packages (manifest dependency graph)"
    echo
    echo '```mermaid'
    awk '
      # mermaid ids read like the path itself; a prefix is added ONLY when the sanitized
      # name would collide with a mermaid keyword or start with a non-letter.
      function mid(s) {
        gsub(/[^A-Za-z0-9_]/, "_", s)
        if (s ~ /^[^A-Za-z]/ || s ~ /^(end|graph|subgraph|flowchart|direction|click|style|class|classDef|linkStyle|default)$/) s = "n_" s
        return s
      }
      /  map: \.ai\/symbols\// {
        dir = $1; name = ""; deps = ""
        if ($2 ~ /^\[/) name = $3
        # "deps-> " is 7 chars — +6 kept the leading space and silently dropped every
        # FIRST dependency from the graph (found via missing domain-model edges).
        if (match($0, /deps-> [^ ]+/)) deps = substr($0, RSTART + 7, RLENGTH - 7)
        if (name != "" && name != "?") byname[name] = dir
        row[++n] = dir "\t" deps
      }
      END {
        print "flowchart LR"
        for (i = 1; i <= n; i++) {
          split(row[i], a, "\t"); dir = a[1]
          if (dir == ".") continue
          printf "  %s[\"%s\"]\n", mid(dir), dir
        }
        for (i = 1; i <= n; i++) {
          split(row[i], a, "\t"); dir = a[1]; deps = a[2]
          if (deps == "" || dir == ".") continue
          m = split(deps, dl, ",")
          for (j = 1; j <= m; j++) if (dl[j] in byname)
            printf "  %s --> %s\n", mid(dir), mid(byname[dl[j]])
        }
      }
    ' "$OUT"
    echo '```'
    echo
    echo "## unit maps"
    echo
    echo "| unit | map |"
    echo "|---|---|"
    awk '/  map: \.ai\/symbols\// && $1 != "." { p = $NF; rel = substr(p, 13); print "| " $1 " | [" rel "](" rel ") |" }' "$OUT" | LC_ALL=C sort -u
    # Root leftovers: source files at repo level that no unit owns (dot-dirs excluded).
    # In a packaged monorepo this is empty and prints nothing; in a flat repo this IS the map.
    local RW; RW="$(mktemp -d)"
    unit_files "." | LC_ALL=C sort > "$RW/files"
    if [ -s "$RW/files" ]; then
      echo
      echo "> root fingerprint: $(while IFS= read -r f; do [ -f "$f" ] && cksum "$f"; done < "$RW/files" | cksum | awk '{print $1" "$2}')"
      echo
      echo "## files at repo root (owned by no package)"
      extract_symbols < "$RW/files" > "$RW/syms" || true
      while IFS= read -r f; do
        echo
        echo "### $f"
        echo
        echo "| name | kind | line |"
        echo "|---|---|---|"
        awk -F "\t" -v f="$f" '$1 == f { printf "| %s | %s | %s |\n", $3, $2, $4 }' "$RW/syms"
      done < "$RW/files"
    fi
    rm -rf "$RW"
  } > "$out"
  [ -z "$PREV" ] || { map_delta "$PREV" "$out" "$out"; rm -f "$PREV"; }
  echo "$out"
}

# --symbols-all: build the WHOLE atlas — INDEX + every unit's maps — and GC everything
# generated that no longer belongs (old .tsv indexes migrate away here automatically).
if [ "${1:-}" = "--symbols-all" ]; then
  # Regenerate the snapshot when stale OR when it predates the atlas format (a
  # fingerprint-fresh snapshot can still carry old "symbols:" rows — migration).
  { [ -f "$OUT" ] && grep -q '  map: \.ai/symbols/' "$OUT" && bash "$0" --check >/dev/null 2>&1; } || bash "$0" >/dev/null
  UNITS="$(awk '/  map: \.ai\/symbols\//{print $1}' "$OUT" | sort -u)"
  [ -n "$UNITS" ] || { echo "no units found in snapshot"; exit 1; }
  UNITS_ALL="$UNITS"  # ownership must reflect the snapshot just regenerated, not a stale one
  VALID="$(mktemp)"; trap 'rm -f "$VALID"' EXIT
  write_index_md >> "$VALID" || { echo "failed writing INDEX.md" >&2; exit 1; }
  N=0
  while IFS= read -r un; do
    [ -n "$un" ] && [ "$un" != "." ] || continue   # "." lives inside INDEX.md
    case "$un" in /*|*..*) echo "skipping unsafe unit dir: $un" >&2; continue ;; esac
    write_unit_maps "$un" >> "$VALID" || { echo "failed mapping unit: $un" >&2; exit 1; }
    N=$((N + 1))
  done <<UEOF
$UNITS
UEOF
  # GC: generated files not written this run are stale maps an AI might trust — including
  # every old-scheme .tsv. Only files carrying a generated marker are ever touched;
  # .baseline files are task-scoped scratch owned by the --baseline/--diff flow.
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    case "$f" in *.baseline) continue ;; esac
    grep -Fq "$GEN_MARK" "$f" 2>/dev/null \
      || grep -q '^# parent: \.ai/PROJECT_SNAPSHOT\.md\|^# usage graph:' "$f" 2>/dev/null || continue
    grep -Fxq "$f" "$VALID" && continue
    rm -f "$f"
    echo "removed stale map: $f"
  done < <(find .ai/symbols -type f \( -name '*.md' -o -name '*.tsv' \) 2>/dev/null)
  find .ai/symbols -mindepth 1 -type d -empty -delete 2>/dev/null || true
  echo "atlas: INDEX.md + $N unit maps -> .ai/symbols/"
  exit 0
fi

# --changed [<dir>]: what did the working tree change vs git HEAD, at symbol level?
# AI triggers this per file/dir to see added/removed/moved functions without any saved
# baseline — git IS the baseline. Body-only edits don't move symbols: see `git diff` for lines.
if [ "${1:-}" = "--changed" ]; then
  SCOPE="${2:-.}"; SCOPE="${SCOPE%/}"; [ -n "$SCOPE" ] || SCOPE="."
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "--changed requires a git repository" >&2; exit 2; }
  W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
  # --relative: we may be a nested scope inside a bigger git repo — paths must be
  # cwd-relative or the on-disk lookups (and the AI's next read) point at nothing.
  { git diff --name-only --relative HEAD -- "$SCOPE" 2>/dev/null
    git ls-files --others --exclude-standard -- "$SCOPE"; } \
    | { grep -E "$SRC_EXT_RE" || true; } | { grep -v '^\.ai/' || true; } \
    | LC_ALL=C sort -u > "$W/files"
  [ -s "$W/files" ] || { echo "no changed source files under $SCOPE (vs HEAD)"; exit 0; }
  : > "$W/old.tsv"; : > "$W/new.tsv"
  while IFS= read -r f; do
    ext="${f##*.}"
    if git show "HEAD:./$f" > "$W/old-copy.$ext" 2>/dev/null; then
      printf '%s\n' "$W/old-copy.$ext" | extract_symbols \
        | awk -v f="$f" 'BEGIN { FS = OFS = "\t" } { $1 = f; print }' >> "$W/old.tsv"
    fi
    [ -f "$f" ] && printf '%s\n' "$f" | extract_symbols >> "$W/new.tsv"
  done < "$W/files"
  CHANGES="$(awk -F '\t' '
    NR == FNR { old[$1 FS $2 FS $3] = $4; next }
    { k = $1 FS $2 FS $3
      if (!(k in old)) print "+ " $2 " " $3 " " $1 ":" $4
      else { if (old[k] != $4) print "~ " $2 " " $3 " " $1 ":" old[k] "->" $4; delete old[k] } }
    END { for (k in old) { split(k, a, FS); print "- " a[2] " " a[3] " " a[1] ":" old[k] } }
  ' "$W/old.tsv" "$W/new.tsv" | LC_ALL=C sort)"
  echo "changed source files vs HEAD under $SCOPE:"
  sed 's/^/  /' "$W/files"
  if [ -z "$CHANGES" ]; then
    echo "no symbol-level changes (body-only edits — see: git diff)"; exit 0
  fi
  echo "symbol changes (+added -removed ~moved); body-only edits not shown — see git diff:"
  printf '%s\n' "$CHANGES"
  exit 1
fi

# --refresh [<dir>]: the task-completion trigger. Finds what changed vs git HEAD, maps each
# changed file to its owning unit, regenerates exactly those units' maps (+ INDEX), and
# prints the trace — after a task the atlas reflects reality with minimal work.
if [ "${1:-}" = "--refresh" ]; then
  SCOPE="${2:-.}"; SCOPE="${SCOPE%/}"; [ -n "$SCOPE" ] || SCOPE="."
  case "$SCOPE" in /*|*..*) echo "scope must be repo-relative: $SCOPE" >&2; exit 1 ;; esac
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "--refresh requires a git repository" >&2; exit 2; }
  [ -n "$UNITS_ALL" ] || { echo "no atlas yet — run: .coder-ai-os-script/update-ai-context.sh --symbols-all"; exit 1; }
  CHANGED="$({ git diff --name-only --relative HEAD -- "$SCOPE" 2>/dev/null
               git ls-files --others --exclude-standard -- "$SCOPE"; } \
             | { grep -E "$SRC_EXT_RE" || true; } | { grep -v '^\.ai/' || true; } | LC_ALL=C sort -u)"
  [ -n "$CHANGED" ] || { echo "nothing changed vs HEAD under $SCOPE — atlas already current"; exit 0; }
  AFFECTED="$(awk '
    NR == FNR { ua[++n] = $0; next }
    { best = "."
      for (i = 1; i <= n; i++) if (ua[i] != "" && ua[i] != "." && index($0, ua[i] "/") == 1 && length(ua[i]) > length(best)) best = ua[i]
      print best }
  ' <(printf '%s\n' "$UNITS_ALL") <(printf '%s\n' "$CHANGED") | sort -u)"
  echo "changed files vs HEAD:"
  printf '%s\n' "$CHANGED" | sed 's/^/  /'
  echo "refreshing maps:"
  while IFS= read -r un; do
    [ -n "$un" ] && [ "$un" != "." ] || continue   # root-level changes land in INDEX.md below
    write_unit_maps "$un" | sed 's/^/  /'
  done <<REOF
$AFFECTED
REOF
  write_index_md | sed 's/^/  /'
  echo "atlas refreshed for $(printf '%s\n' "$AFFECTED" | grep -c .) unit(s) — the files traced above are done"
  exit 0
fi

if [ "${1:-}" = "--symbols" ]; then
  DIR="${2:-.}"; DIR="${DIR%/}"; [ -n "$DIR" ] || DIR="."
  case "$DIR" in /*|*..*) echo "unit dir must be repo-relative: $DIR" >&2; exit 1 ;; esac
  [ -d "$DIR" ] || { echo "no such directory: $DIR" >&2; exit 1; }
  MOUT="$(map_out "$DIR")"
  if [ "${3:-}" = "--check" ]; then
    [ -f "$MOUT" ] || { echo "map missing — run: .coder-ai-os-script/update-ai-context.sh --symbols $DIR"; exit 1; }
    if [ "$DIR" = "." ]; then  # INDEX: structural fingerprint + root leftovers (if any)
      STORED="$(sed -n 's/^> Fingerprint: \([0-9]* [0-9]*\).*/\1/p' "$MOUT" | head -1)"
      RSTORED="$(sed -n 's/^> root fingerprint: \([0-9]* [0-9]*\).*/\1/p' "$MOUT" | head -1)"
      if [ "$STORED" = "$FINGERPRINT" ] && { [ -z "$RSTORED" ] || [ "$RSTORED" = "$(unit_fingerprint .)" ]; }; then
        echo "map fresh: $MOUT"; exit 0
      fi
      echo "map STALE — regenerate: .coder-ai-os-script/update-ai-context.sh --symbols ."; exit 1
    fi
    STORED="$(sed -n 's/^> fingerprint: \([0-9]* [0-9]*\).*/\1/p' "$MOUT" | head -1)"
    if [ "$STORED" = "$(unit_fingerprint "$DIR")" ]; then echo "map fresh: $MOUT"; exit 0; fi
    echo "map STALE — regenerate: .coder-ai-os-script/update-ai-context.sh --symbols $DIR"; exit 1
  fi
  if [ "${3:-}" = "--baseline" ]; then
    BOUT=".ai/symbols/$(unit_name "$DIR").baseline"
    md_guard "$BOUT" || exit 1
    { echo "# task-scoped baseline — $GEN_MARK"; unit_files "$DIR" | extract_symbols; } > "$BOUT"
    echo "baseline: $BOUT"; exit 0
  fi
  if [ "${3:-}" = "--diff" ]; then
    BOUT=".ai/symbols/$(unit_name "$DIR").baseline"
    [ -f "$BOUT" ] || { echo "no baseline — run: .coder-ai-os-script/update-ai-context.sh --symbols $DIR --baseline" >&2; exit 2; }
    W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
    unit_files "$DIR" | extract_symbols > "$W/new.tsv" || true
    CHANGES="$(awk -F '\t' '
      NR == FNR { if ($0 !~ /^#/) old[$1 FS $2 FS $3] = $4; next }
      /^#/ { next }
      { k = $1 FS $2 FS $3
        if (!(k in old)) print "+ " $2 " " $3 " " $1 ":" $4
        else { if (old[k] != $4) print "~ " $2 " " $3 " " $1 ":" old[k] "->" $4; delete old[k] } }
      END { for (k in old) { split(k, a, FS); print "- " a[2] " " a[3] " " a[1] ":" old[k] } }
    ' "$BOUT" "$W/new.tsv" | LC_ALL=C sort)"
    if [ -z "$CHANGES" ]; then echo "no structural changes vs baseline"; exit 0; fi
    echo "structural changes vs baseline (+added -removed ~moved) — verify each against the"
    echo "task's declared Files; changes OUTSIDE declared scope are unrelated edits to flag:"
    printf '%s\n' "$CHANGES"; exit 1
  fi
  if [ "$DIR" = "." ]; then write_index_md | sed 's/^/wrote /'; else write_unit_maps "$DIR" | sed 's/^/wrote /'; fi
  exit 0
fi

# --graph <dir>: enrich the unit's maps with used-by + classification (import-confirmed
# word-match; tests/entries/private classified BEFORE anything is flagged "verify").
if [ "${1:-}" = "--graph" ]; then
  DIR="${2:-.}"; DIR="${DIR%/}"; [ -n "$DIR" ] || DIR="."
  case "$DIR" in /*|*..*) echo "unit dir must be repo-relative: $DIR" >&2; exit 1 ;; esac
  [ -d "$DIR" ] || { echo "no such directory: $DIR" >&2; exit 1; }
  [ "$DIR" != "." ] || { echo "the repo level has no rich mode — enrich per package: --graph <unit-dir> (units: .ai/symbols/INDEX.md)"; exit 0; }
  write_unit_maps "$DIR" rich | sed 's/^/wrote /'
  exit 0
fi
# ---------- end symbol index ----------

# --check: is the existing snapshot still fresh? Structural only — the fingerprint is a
# checksum of the tracked-path LIST (never contents), so it changes exactly when files are
# added/removed/renamed. Exit 0 fresh, 1 stale/missing. Agents run this before trusting the map.
if [ "${1:-}" = "--check" ]; then
  [ -f "$OUT" ] || { echo "snapshot missing — run .coder-ai-os-script/update-ai-context.sh"; exit 1; }
  STORED="$(sed -n 's/^> Fingerprint: \([0-9]* [0-9]*\).*/\1/p' "$OUT" | head -1)"
  [ -n "$STORED" ] || { echo "snapshot has no fingerprint (user-owned or pre-fingerprint) — cannot check"; exit 0; }
  if [ "$STORED" = "$FINGERPRINT" ]; then echo "snapshot fresh"; exit 0; fi
  echo "snapshot STALE — regenerate: .coder-ai-os-script/update-ai-context.sh"; exit 1
fi

mkdir -p "$OUT_DIR"
[ ! -L "$OUT" ] || { echo "refusing symlink output: $OUT" >&2; exit 1; }
[ ! -f "$OUT" ] || grep -Eq 'Generated by `(?:scripts|\.coder-ai-os-script)/update-ai-context\.sh`' "$OUT" || { echo "kept user-owned snapshot: $OUT"; exit 0; }

# The report body is best-effort formatting: `head -N` truncation legitimately makes
# upstream commands exit via SIGPIPE (141), and empty grep matches return 1. Relax
# errexit/pipefail here so a truncated or empty section never aborts the whole write.
set +e +o pipefail

{
  echo "# Project Snapshot"
  echo
  echo "> Generated by \`.coder-ai-os-script/update-ai-context.sh\` — do not hand-edit."
  echo "> Deterministic structural facts only. Regenerate when the repo's shape changes."
  echo "> Use rg for cheap location; use the code index (CodeGraph MCP) for caller/impact queries;"
  echo "> this file is the orientation fallback. Read it only when repo-wide orientation is needed."
  echo "> Fingerprint: $FINGERPRINT (path-list checksum). Verify freshness BEFORE trusting this map:"
  echo "> \`.coder-ai-os-script/update-ai-context.sh --check\` — if STALE, regenerate first."
  echo "> Memory scope: $(memory_scope)"
  echo

  echo "## Languages (by tracked file extension)"
  echo '```'
  printf '%s\n' "$FILES" \
    | sed -n 's|.*/||; s|^.*\.\([A-Za-z0-9_]*\)$|\1|p' \
    | grep -vE '^[0-9]+$' \
    | sort | uniq -c | sort -nr | head -15
  echo '```'
  echo

  echo "## Top-level structure (depth 2)"
  echo '```'
  find . -maxdepth 2 \
    -not -path './.git' -not -path './.git/*' \
    -not -path './node_modules' -not -path './node_modules/*' \
    -not -path '*/.env*' \
    -not -path './.codegraph' -not -path './.codegraph/*' \
    2>/dev/null | sed 's|^\./||' | sort | head -200
  echo '```'
  echo

  echo "## Build / manifest files"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(package\.json|pnpm-workspace\.yaml|tsconfig\.json|pyproject\.toml|setup\.py|requirements\.txt|Cargo\.toml|go\.mod|pom\.xml|build\.gradle|Gemfile|composer\.json|Makefile|CMakeLists\.txt|Dockerfile|docker-compose\.ya?ml)$' \
    | sort || echo "(none found)"
  echo '```'
  echo

  echo "## Workspace packages / indexable units (heuristic monorepo map)"
  echo "Package -> manifest -> name -> internal deps -> its atlas map (L1). Work owner-first,"
  echo "one package in flight (monorepo-change skill); pick the owning unit here without scanning."
  echo "Atlas (folder/file graphs + symbol tables): .ai/symbols/INDEX.md; per unit on demand:"
  echo '  .coder-ai-os-script/update-ai-context.sh --symbols <dir>          (writes .ai/symbols/<dir>.md maps)'
  echo '  .coder-ai-os-script/update-ai-context.sh --symbols <dir> --check  (fresh? STALE = regenerate first)'
  echo '  .coder-ai-os-script/update-ai-context.sh --graph <dir>            (enrich maps: used-by + classified'
  echo '                                                         unreferenced-symbol verification)'
  echo '  .coder-ai-os-script/update-ai-context.sh --refresh                (after a task: regenerate exactly'
  echo '                                                         the maps your changes touched)'
  echo "Usages of a symbol across the app: find which units depend on its owner (deps below +"
  echo "module flow), then rg -w <name> ONLY inside those dirs — never a repo-wide scan."
  echo "What did I change? .coder-ai-os-script/update-ai-context.sh --changed <dir> — added/removed/moved"
  echo "functions vs git HEAD, per file (body-only edits: git diff)."
  echo '```'
  # E1 — source root: nested projects (src/sat/backend/...) hide their modules behind
  # wrapper dirs. The longest common directory prefix of all source files is the honest
  # graph root; units and flow are computed one segment BELOW it. Empty prefix = repo root
  # (multiple clusters at top level) = previous behavior.
  SRCROOT="$(printf '%s\n' "$FILES" | grep -E "$SRC_EXT_RE" | awk -F/ '
    NR == 1 { n = NF - 1; for (i = 1; i <= n; i++) p[i] = $i; next }
    { m = NF - 1; if (m < n) n = m
      for (i = 1; i <= n; i++) if (p[i] != $i) { n = i - 1; break } }
    END { s = ""; for (i = 1; i <= n; i++) s = s (i > 1 ? "/" : "") p[i]; print s }')"
  STRIP="${SRCROOT:+$SRCROOT/}"
  [ -n "$SRCROOT" ] && echo "source root: $SRCROOT (longest common source prefix; units live below it)"
  TOPS="$(printf '%s\n' "$FILES" | grep -E "$SRC_EXT_RE" \
    | awk -v r="$STRIP" '{ if (r != "") { if (index($0, r) != 1) next; $0 = substr($0, length(r) + 1) } print }' \
    | grep '/' | cut -d/ -f1 | sort -u \
    | grep -vE '^(node_modules|vendor|dist|build|target|docs?)$' | grep -v '^\.' | head -30)"
  PKG_MANIFESTS="$(printf '%s\n' "$FILES" \
    | grep -E '(^|/)(package\.json|pyproject\.toml|setup\.py|Cargo\.toml|go\.mod|pom\.xml|build\.gradle|composer\.json)$' \
    | grep '/' \
    | grep -vE '(^|/)(node_modules|vendor|dist|build|target|\.venv|venv)/' | head -60)"
  if [ -z "$PKG_MANIFESTS" ]; then
    echo "(no nested manifests — single-package repo)"
  else
    MAP_TMP="$(mktemp)"; NAMES_TMP="$(mktemp)"
    true > "$MAP_TMP"
    while IFS= read -r m; do
      [ -f "$m" ] || continue
      d="${m%/*}"
      case "$m" in
        */package.json)   n="$(sed -n 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$m" | head -1)" ;;
        */Cargo.toml)     n="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$m" | head -1)" ;;
        */pyproject.toml) n="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$m" | head -1)" ;;
        */go.mod)         n="$(sed -n 's/^module[[:space:]]*//p' "$m" | head -1)" ;;
        *)                n="" ;;
      esac
      printf '%s\t%s\t%s\n' "$d" "${m##*/}" "${n:-?}" >> "$MAP_TMP"
    done <<PKGEOF
$PKG_MANIFESTS
PKGEOF
    cut -f3 "$MAP_TMP" | grep -v '^?$' | sort -u > "$NAMES_TMP"
    # Phantom-unit filter: a nested manifest whose name can't be resolved (a stray
    # setup.py deep inside another package's source) is NOT a real unit — its files
    # belong to the enclosing package's maps.
    awk -F '\t' '
      NR == FNR { dirs[$1] = 1; next }
      {
        if ($3 == "?") { for (d in dirs) if (d != $1 && index($1, d "/") == 1) next }
        print
      }
    ' "$MAP_TMP" "$MAP_TMP" > "$MAP_TMP.f" && mv "$MAP_TMP.f" "$MAP_TMP"
    while IFS="$(printf '\t')" read -r d mf n; do
      deps=""
      if [ -s "$NAMES_TMP" ] && [ -f "$d/$mf" ]; then
        deps="$({ grep -oE '"[^"[:space:]]+"' "$d/$mf" | tr -d '"'; \
                  sed -n 's/^\([A-Za-z0-9_.@/-]\{1,\}\)[[:space:]]*=.*/\1/p' "$d/$mf"; } \
                | sort -u | grep -Fxf "$NAMES_TMP" 2>/dev/null \
                | grep -Fxv "$n" | head -8 | paste -sd, -)"
      fi
      if [ -n "$deps" ]; then printf '%s  [%s]  %s  deps-> %s  map: %s\n' "$d" "$mf" "$n" "$deps" "$(map_out "$d")"
      else printf '%s  [%s]  %s  map: %s\n' "$d" "$mf" "$n" "$(map_out "$d")"; fi
    done < "$MAP_TMP"
    rm -f "$MAP_TMP" "$NAMES_TMP"
  fi
  # Bare units: source dirs one segment below the source root, no manifest required
  # (works in repos with no pyproject/package.json at all) — plus the source root and
  # repo root, so nested, single-package, and flat repos all get the same L0->L1->L2 chain.
  # Paths printed are full repo-relative so the --symbols command is copy-pasteable.
  while IFS= read -r t; do
    [ -n "$t" ] || continue
    printf '%s\n' "$PKG_MANIFESTS" | grep -q "^$STRIP$t/" && continue
    printf '%s\n' "$FILES" | grep -E "^$STRIP$t/" | grep -qE "$SRC_EXT_RE" || continue
    printf '%s  (no manifest)  map: %s\n' "$STRIP$t" "$(map_out "$STRIP$t")"
  done <<TOPSEOF
$TOPS
TOPSEOF
  [ -n "$SRCROOT" ] && echo "$SRCROOT  (source root)  map: $(map_out "$SRCROOT")"
  echo ".  (repo root)  map: $(map_out .)"
  echo '```'
  echo

  echo "## Module flow (heuristic top-level import graph)"
  echo "Directed edges between top-level dirs, aggregated from import/use/require lines and"
  echo "layered top-to-bottom: [entry] imports others; [base] is imported (api -> ... -> db)."
  echo "File-level only. For function/class callers/impact use the code index (CodeGraph MCP)."
  echo '```'
  if [ "$(printf '%s\n' "$TOPS" | grep -c .)" -lt 2 ]; then
    echo "(fewer than two top-level source dirs — no graph)"
  else
    TOPS_CSV="$(printf '%s\n' "$TOPS" | paste -sd, -)"
    EDGE_LINES="$(grep -rnE \
      --include='*.py' --include='*.ts' --include='*.tsx' --include='*.js' --include='*.jsx' \
      --include='*.go' --include='*.rs' --include='*.rb' --include='*.java' --include='*.php' \
      --include='*.cs' --include='*.sh' \
      --exclude-dir=node_modules --exclude-dir=vendor --exclude-dir=dist --exclude-dir=build \
      --exclude-dir=target --exclude-dir=.git --exclude-dir=.venv --exclude-dir=venv --exclude-dir=.ai \
      '^[[:space:]]*(import|from|use|require|include|source)[[:space:](]' . 2>/dev/null \
      | awk -v tops="$TOPS_CSV" -v sroot="$STRIP" '
          BEGIN {
            n = split(tops, T, ",")
            for (i = 1; i <= n; i++) { Tesc[i] = T[i]; gsub(/[][().*+?^$\\|{}]/, "\\\\&", Tesc[i]) }
          }
          {
            p1 = index($0, ":"); if (p1 == 0) next
            src = substr($0, 1, p1 - 1); sub(/^\.\//, "", src)
            if (sroot != "") { if (index(src, sroot) != 1) next; src = substr(src, length(sroot) + 1) }
            k = index(src, "/"); if (k == 0) next
            s = substr(src, 1, k - 1)
            rest = substr($0, p1 + 1); p2 = index(rest, ":"); if (p2 == 0) next
            line = substr(rest, p2 + 1)
            for (i = 1; i <= n; i++) {
              if (T[i] == s) continue
              if (line ~ ("(^|[^A-Za-z0-9_])" Tesc[i] "($|[^A-Za-z0-9_-])")) e[s "->" T[i]]++
            }
          }
          END { for (x in e) print e[x], x }' \
      | sort -rn | head -15)"
    if [ -z "$EDGE_LINES" ]; then
      echo "(no cross-directory imports detected)"
    else
      printf '%s\n' "$EDGE_LINES" | awk '
        { split($2, p, "->"); out[p[1]] += $1; inn[p[2]] += $1; seen[p[1]]; seen[p[2]] }
        END {
          e = ""; m = ""; b = ""
          for (d in seen) {
            if (out[d] && !inn[d]) e = e d " "
            else if (inn[d] && !out[d]) b = b d " "
            else m = m d " "
          }
          if (e != "") print "[entry] " e
          if (m != "") print "[mid]   " m
          if (b != "") print "[base]  " b
        }'
      echo "--- flow tree (imports point down; cycles marked) ---"
      printf '%s\n' "$EDGE_LINES" | LC_ALL=C sort -k2,2 | awk '
        function ptree(d, pref,   n, arr, i, c, j, m, conn, cpref) {
          onpath[d] = 1; printed[d] = 1
          n = split(ch[d], arr, ","); m = 0
          for (i = 1; i <= n; i++) if (arr[i] != "") m++
          j = 0
          for (i = 1; i <= n; i++) {
            c = arr[i]; if (c == "") continue; j++
            conn = (j == m) ? "`-> " : "|-> "
            cpref = (j == m) ? "    " : "|   "
            if (c in onpath)        print pref conn c "  <- cycle"
            else if (c in printed)  print pref conn c "  (shown above)"
            else { print pref conn c; ptree(c, pref cpref) }
          }
          delete onpath[d]
        }
        { split($2, p, "->")
          if (!(p[1] in idx)) { order[++N] = p[1]; idx[p[1]] }
          if (!(p[2] in idx)) { order[++N] = p[2]; idx[p[2]] }
          ch[p[1]] = ch[p[1]] p[2] ","
          inn[p[2]]++; out[p[1]]++ }
        END {
          for (i = 1; i <= N; i++) { d = order[i]
            if (out[d] && !inn[d] && !(d in printed)) { print d; ptree(d, "") } }
          for (i = 1; i <= N; i++) { d = order[i]
            if (out[d] && !(d in printed)) { print d "  (in a cycle)"; ptree(d, "") } }
        }'
      echo "--- edges (count src->dst) ---"
      printf '%s\n' "$EDGE_LINES"
    fi
  fi
  echo '```'
  echo

  echo "## Entry points (heuristic)"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(main|index|app|server|cli|__main__)\.[A-Za-z]+$|(^|/)cmd/[^/]+/main\.go$' \
    | sort | head -40 || echo "(none found)"
  echo '```'
  echo

  echo "## Test directories"
  echo '```'
  printf '%s\n' "$FILES" \
    | grep -E '(^|/)(tests?|__tests__|spec|e2e)/' \
    | sed 's|/[^/]*$||' | sort -u | head -50 || echo "(none found)"
  echo '```'
} > "$OUT"

set -e -o pipefail

echo "wrote $OUT"
